GuLiEdu/GuLiEdu/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


# xadmin
import xadmin
from users.views import IndexView
# xadmin.autodiscover()


urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    # re_path('^', include('users.urls', namespace='users')),
    # re_path('^', include('courses.urls', namespace='courses')),
    # re_path('^', include('operations.urls', namespace='operations')),
    # re_path('^', include('orgs.urls', namespace='orgs')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^courses/', include(('courses.urls', 'courses'), namespace='courses')),
    url(r'^operations/', include(('operations.urls', 'operations'), namespace='operations')),
    url(r'^orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^ueditor/', include('DjangoUeditor.urls')),
]

handler404 = 'users.views.handler_404'
handler500 = 'users.views.handler_500'

GuLiEdu/apps/courses/urls.py
from django.conf.urls import url
from .views import course_list
from .views import course_detail
from .views import course_video
from .views import course_comment


urlpatterns = [
    url(r'^course_list$', course_list, name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

GuLiEdu/apps/operations/urls.py
from django.conf.urls import url
from .views import user_ask
from .views import user_love
from .views import user_comment
from .views import user_deletelove

urlpatterns = [
    url(r'^user_ask/$', user_ask, name='user_ask'),
    url(r'^user_love/$', user_love, name='user_love'),
    url(r'^user_deletelove/$', user_deletelove, name='user_deletelove'),
    url(r'^user_comment/$', user_comment, name='user_comment'),

]

GuLiEdu/apps/orgs/urls.py
from django.conf.urls import url
# from django.contrib import admin
# from django.urls import path, include
from .views import org_list
from .views import org_detail
from .views import org_detail_course
from .views import org_detail_desc
from .views import org_detail_teacher
from .views import teacher_list
from .views import teacher_detail

urlpatterns = [
    url(r'^org_list/$', org_list, name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teacher/(\d+)/$', org_detail_teacher, name='org_detail_teacher'),

    url(r'^teacher_list/$', teacher_list, name='teacher_list'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),

]

GuLiEdu/extra_apps/DjangoUeditor/DUSite/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
import settings
from django.contrib import admin
from TestApp.views import  TestUEditorModel,ajaxcmd,TestUEditor

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^test/$',TestUEditorModel),
    url(r'^test2/$',TestUEditor),
    url(r'^ajaxcmd/$',ajaxcmd)

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
        url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
        url(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    )

GuLiEdu/extra_apps/DjangoUeditor/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

GuLiEdu/apps/courses/models.py
from datetime import datetime

from django.db import models


# Create your models here.
from orgs.models import OrgInfo
from orgs.models import TeacherInfo


class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/', max_length=200, verbose_name="课程封面")
    name = models.CharField(max_length=20, verbose_name="课程名称")
    course_time = models.IntegerField(default=0, verbose_name="学习时长")
    learn_num = models.IntegerField(default=0, verbose_name="学习人数")
    level = models.CharField(choices=(('senior', '高级'), ("middle", '中级'), ('junior', '初级')),
                             max_length=10, verbose_name='课程难度', default='junior')
    desc = models.CharField(max_length=200, verbose_name="机构简介")
    detail = models.TextField(verbose_name="机构详情")
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    click_num = models.IntegerField(default=0, verbose_name="访问量")
    category = models.CharField(choices=(('frontend', '前端开发'), ('backend', '后端开发')),
                                max_length=10, verbose_name="课程类别")
    course_notice = models.CharField(max_length=200, verbose_name='课程公告')
    course_need = models.CharField(max_length=100, verbose_name='课程须知')
    teacher_said = models.CharField(max_length=100, verbose_name='老师指导')
    orginfo = models.ForeignKey(OrgInfo, verbose_name='所属机构', on_delete=models.CASCADE)
    teacherinfo = models.ForeignKey(TeacherInfo, verbose_name='所属讲师', on_delete=models.CASCADE)
    is_banner = models.BooleanField(default=False, verbose_name='是否轮播')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name


class LessonInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='章节名称')
    courseinfo = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "章节信息"
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='视频名称')
    learn_time = models.IntegerField(default=0, verbose_name='视频时长')
    url = models.URLField(default="http://www.atguigu.com", max_length=200, verbose_name='视频链接')
    lessioninfo = models.ForeignKey(LessonInfo, verbose_name="所属章节", on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "视频信息"
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name='资源名称')
    # FileField 可以下载
    down_load = models.FileField(upload_to='source/', max_length=200, verbose_name='下载路径')
    courseinfo = models.ForeignKey(CourseInfo, verbose_name='所属课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "资源信息"
        verbose_name_plural = verbose_name

GuLiEdu/apps/operations/models.py
from datetime import datetime

from django.db import models

# Create your models here.
from courses.models import CourseInfo
from users.models import UserProfile


class UserAsk(models.Model):
    name = models.CharField(max_length=50, verbose_name='姓名')
    phone = models.CharField(max_length=11, verbose_name='手机号码')
    course = models.CharField(max_length=20, verbose_name='课程名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '咨询信息'
        verbose_name_plural = verbose_name


class UserLove(models.Model):
    love_man = models.ForeignKey(UserProfile, verbose_name='收藏用户', on_delete=models.CASCADE)
    love_id = models.IntegerField(verbose_name='收藏id')
    love_type = models.IntegerField(choices=((1, 'course'), (2, 'teacher'), (3, 'org')), verbose_name='收藏类别')
    love_status = models.BooleanField(default=False, verbose_name="收藏状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name='收藏时间')

    def __str__(self):
        return self.love_man.username      # 没有xfile, 通过love_man找到username

    class Meta:
        verbose_name = '收藏信息'
        verbose_name_plural = verbose_name


class UserCourse(models.Model):
    learn_man = models.ForeignKey(UserProfile, verbose_name='学习用户', on_delete=models.CASCADE)
    # 多对多过程，同一用户可以学习多门课程，同理  相当于中间表 中间第三张用于维护课程和用户学习的关系
    learn_course = models.ForeignKey(CourseInfo, verbose_name='学习课程', on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='学习时间')

    def __str__(self):
        return self.learn_man.username  # 没有xfile, 通过love_man找到username

    class Meta:
        # 联合唯一 不会重复添加
        unique_together = ('learn_man', 'learn_course')
        verbose_name = '用户学习课程信息'
        verbose_name_plural = verbose_name


class UserComment(models.Model):
    comment_man = models.ForeignKey(UserProfile, verbose_name='评论用户', on_delete=models.CASCADE)
    comment_course = models.ForeignKey(CourseInfo, verbose_name='评论课程', on_delete=models.CASCADE)
    comment_content = models.CharField(max_length=300, verbose_name='评论内容')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='评论时间')

    def __str__(self):
        return self.comment_content    # comment_content ?

    class Meta:
        verbose_name = '用户评论课程信息'
        verbose_name_plural = verbose_name


class UserMessage(models.Model):
    # 后台系统消息
    message_man = models.IntegerField(default=0, verbose_name='消息用户')
    message_content = models.CharField(max_length=200, verbose_name='消息内容')
    message_status = models.BooleanField(default=False, verbose_name="消息状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.message_content

    class Meta:
        verbose_name = '用户消息信息'
        verbose_name_plural = verbose_name

GuLiEdu/apps/orgs/models.py
from datetime import datetime

from django.db import models
from DjangoUeditor.models import UEditorField
# from DjangoUeditor.models import UEditorField

# Create your models here.


class CityInfo(models.Model):
    name = models.CharField(max_length=20, verbose_name="城市名称")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/', max_length=200, verbose_name="机构封面")
    name = models.CharField(max_length=20, verbose_name="机构名称")
    course_num = models.IntegerField(default=0, verbose_name="课程数")
    learn_num = models.IntegerField(default=0, verbose_name="学习人数")
    address = models.CharField(max_length=200, verbose_name="机构地址")
    desc = models.CharField(max_length=200, verbose_name="机构简介")
    detail = UEditorField(verbose_name='机构详情', width=700, height=400, toolbars='full', imagePath='ueditor/images/',
                          filePath='ueditor/files/', upload_settings={'imageMaxSizing': 1024000}, default='')
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    click_num = models.IntegerField(default=0, verbose_name="访问量")
    category = models.CharField(choices=(('train_org', '培训机构'), ('colleges', '高校'),
                                         ('person', '个人')), max_length=10, verbose_name="机构类别")
    cityinfo = models.ForeignKey(CityInfo, verbose_name="所在城市", on_delete=models.CASCADE)   # 一对多 即同一城市有多个机构
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构信息'
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name="头像")
    name = models.CharField(max_length=20, verbose_name="讲师姓名")
    work_year = models.IntegerField(default=3, verbose_name="工作时间")
    work_position = models.CharField(max_length=20, verbose_name="工作职位")
    work_style = models.CharField(max_length=20, verbose_name="教学特点")
    work_company = models.ForeignKey(OrgInfo, verbose_name="所属机构", on_delete=models.CASCADE)  # 一对多
    age = models.IntegerField(default=30, verbose_name="讲师年龄")
    gender = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='讲师性别', default='boy')
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    click_num = models.IntegerField(default=0, verbose_name="访问量")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '讲师信息'
        verbose_name_plural = verbose_name

GuLiEdu/templates/courses/course_comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    公开课评论 - 谷粒教育网
{% endblock %}

{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'courses:course_detail' %}">课程详情</a>></li>
                <li>课程评论</li>
			</ul>
		</div>
	</div>
</section>


    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value">
                        <strong>
                            {% if course.level == 'senior' %}
                                 高级
                            {% elif course.level == 'middle' %}
                                 中级
                            {% else %}
                                 初级
                            {% endif %}
                        </strong>
                    </span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_time }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.learn_num }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'courses:course_video' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for comment in all_comments  %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.comment_man.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment.comment_man.username }}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comment_content }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                         {% for source in course.sourceinfo_set.all %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ source.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ source.down_load }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                         {% endfor %}
                        </ul>
                    </div>
                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacherinfo.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">{{ course.teacherinfo.name }}</a>
        </span>
                            <span class="job">{{ course.teacherinfo.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.course_need }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_said }}</dd>
                            </dl>
                        </div>
                    </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        {% for course1 in course_list %}
                                        <li class="curr">
                                            <a href="{% url 'courses:course_detail' course1.id %}" target="_blank">
                                                <img src="{{ MEDIA_URL }}{{ course1.image }}" alt="html">
                                                <span class="name autowrap">{{ course1.name }}</span>
                                            </a>
                                        </li>
                                        {% endfor %}

                                    </ul>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>    </div>
            <div class="clear">

            </div>

        </div>

    </div>
</div>
{% endblock %}

{% block myjs %}
    <script>
        $(function () {
            $(' #js-pl-submit').click(function () {
                var comment_course = {{ course.id }};
                var comment_content = $('#js-pl-textarea').val();
                $.ajax({
                    type: 'POST',
                    url: '{% url 'operations:user_comment' %}',
                    data: {
                        comment_content: comment_content,
                        comment_course: comment_course,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success:function (callback) {
                        if (callback.status == 'ok') {
                            alert(callback.msg);
                            window.location.reload();
                            }else {
                                alert(callback.msg);

                        }


                    }
                })
            })

        })
    </script>
{% endblock %}




GuLiEdu/templates/courses/course_video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课视频信息 - 谷粒教育网{% endblock %}
{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css"href="{% static 'css/guli/course/common-less.css' %}">
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value">
                        <strong>
                            {% if course.level == 'senior' %}
                                        高级
                            {% elif course.level == 'middle' %}
                                        中级
                            {% else %}
                                        初级
                            {% endif %}
                        </strong>
                    </span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.course_time }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.learn_num }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'courses:course_video' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course.course_notice }}</a> </div>
                </div>

                <div class="mod-chapters">
                {% for lesson in course.lessoninfo_set.all %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                        {% for video in lesson.videoinfo_set.all %}
                            <li>
                                <a target="_blank" href='{{ video.url }}' class="J-media-item studyvideo">{{ video.name }} ({{ video.learn_time }})
                                    <i class="study-state"></i>
                                </a>
                            </li>

                        {% endfor %}
                        </ul>
                    </div>
                {% endfor %}



                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                        {% for source in course.sourceinfo_set.all %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ source.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ source.down_load }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                        {% endfor %}

                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacherinfo.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}" target="_blank">{{ course.teacherinfo.name }}</a>
        </span>
                            <span class="job">{{ course.teacherinfo.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.course_need }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_said }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">学过该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for course1 in course_list %}
                                    <li class="curr">
                                        <a href="{% url 'courses:course_detail' course1.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ course1.image }}" >
                                            <span class="name autowrap">{{ course1.name }}</span>
                                        </a>
                                    </li>
                                    {% endfor %}


                                </ul>
                            </div>

                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}


